### ISSUE TITLE
Variations on World Schools Style

### ISSUE THREAD

**Issue by 0zlw** [czlee/debatekeeper-formats#2]
Hi CZ, thanks for a great app. I just wanted to raise this as an issue first - I'm happy to make the XML files if you're happy to implement the styles.

I'm with Auckland Schools Debating and we had some feedback from teachers that it would be good if there were apps available that support timing. We have 5 world schools style grades, 3 of which are largely supported by the app.

Premier Advanced - World Schools
Premier Junior/Advanced Open - Thropy but 1 hour prep
Senior Open - 6 minute speeches, no POIs with one bell at 5 minutes
Junior Open - 5 minute speeches, no POIs with one bell at 4 minutes

I was wondering if it would be easier to add these styles as variations to World Schools, rather than as completely new styles  i.e.

Premier Junior/Advanced Open - World Schools (6 minutes)
Senior Open - World Schools (6 minutes, no POIs)
Junior Open - World Schools (5 minutes, no POIs)

We also have an additional Impromtpu Cup tournament modeled on NZ Easters, except with 5 minute speeches and one bell at 4 minutes which is a one off annual thing but would be nice to have. 

Let me know what your preferred approach to this is - I'd like to be able to promote this app with our teachers, especially in Junior/Senior Open which is teacher adjudicated, but you may think we should just stick to custom formats.

**Comment by czlee** [comment]
Well, I suppose this issue has become more relevant to me in the last year 😉

Because updates are so infrequent, in the next update I'm moving to an online repository for formats, which is here, hence the issue transfer. We'll put the formats here, and they'll then be available to users after they update Debatekeeper, after the release goes out later this month.

The formats don't have to be in before the Debatekeeper update (which has to go out this month, because of Android legacy support deadlines), since formats will be distributed separately from the app. They'll just become available whenever they appear in this repository.

**Comment by daankoning** [comment]
@0zlw, do you still need these formats? If so I'd be happy to create them for you.
