### ISSUE TITLE
Version number bump checking doesn't work for pull requests with multiple commits.

### ISSUE THREAD

**Issue by daankoning** [czlee/debatekeeper-formats#20]
For example see #19. What happens is that `github.event.pull_request.base.sha` gives the hash of the commit that the pull request is based on, not the most recent commit. This works fine for the first commit in a PR, but (as in #19) on the second commit it tries to compare the second commit to the commit from before the PR, meaning that in this specific case it takes the base commit as https://github.com/czlee/debatekeeper-formats/commit/943ccb5ec645680f842edd98972d0fd9daed4fe7. 

Running `git show` on this commit while looking for `v1/formats/tgd2022.xml` gives this fatal error:

    path 'v1/formats/tgd2022.xml' exists on disk, but not in '943ccb5ec645680f842edd98972d0fd9daed4fe7'

Not sure how to go about fixing this as there doesn't seem to be an obvious way to tell a github action to "take the second to last commit".

**Comment by czlee** [comment]
It's meant to be the parent of the earliest commit in the PR, which I think is what `github.event.pull_request.base.sha` is? In this case it should be the parent of c701deac132d70e1a615cba2584288be3a4dd68a, which I think is 943ccb5ec645680f842edd98972d0fd9daed4fe7?

In this case `tgd2022.xml` is a new file, of course, but in that case it should just detect that it's a new file and skip the check, which I thought I… actually, now that I think about it, I think I forgot to account for 😬

**Comment by daankoning** [comment]
You're right, the problem is that it's a new file. I think the best way to solve this would be to check for it in the python script, perhaps even just catching this specific error with a try-catch? I imagine any solution involving the github actions syntax would be incredibly cumbersome.

On `github.event.pull_request.base.sha` I ran the script locally a couple times and that appears to be the case, yes.

**Comment by czlee** [comment]
Yeah, in the Python script, I think this option of `git diff` should help:
https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203

(Got there from: https://stackoverflow.com/questions/6894322/how-to-make-git-diff-and-git-log-ignore-new-and-deleted-files)

**Comment by daankoning** [comment]
As far as I'm able to tell the problem only pops up on `git show` so I don't think this would help. Did you notice `git diff` also giving issues?

**Comment by czlee** [comment]
Oh, sorry, let me clarify. The function `check_version_number_increment` should only run on files that are returned by the `git diff` line in the first place:
https://github.com/czlee/debatekeeper-formats/blob/943ccb5ec645680f842edd98972d0fd9daed4fe7/scripts/check_version_bump.py#L21-L29

So the idea is:
1. `git diff --name-only <base_sha> -- v1/formats` returns a list of files that have changed since `<base_sha>`
2. For each file in that list, `git show` grabs the contents of the file as at `<base_sha>`.

This doesn't work because a new file pops up in (1) as a "changed file". So my new idea (not yet tested) would be to use instead
``` bash
git diff --name-only <base_sha> --diff-filter=M -- v1/formats
```
and then hopefully new files (as opposed to modified files) would be excluded from the list altogether, and `git show` wouldn't attempt to run on them.

(I worry a little that trying to catch the error inside `check_version_number_increment` would risk silently catching other errors that cause the same return code.)

…that said, now that I'm thinking about it, maybe skipping those files isn't such a great idea, maybe we should enforce that the first version has to be 1. But then maybe not, since people might distribute formats unofficially before submitting them to the official repo. 🤔

**Comment by czlee** [comment]
Oh, I see, so the error that showed up in #22 is what I thought showed up, but did not show up, in #19, sorry.

I think I read somewhere that in theory, `fetch_depth: ${{ github.event.pull_request.commits }}` isn't meant to work if you want to get the base, because if there are _n_ commits in the PR, then fetching _n_ commits will get you as far as the first commit of the PR, and you still won't have the base commit. But it seemed to be highly nontrivial, since you can't do maths inside a GitHub actions context (_i.e._ `${{ github.event.pull_request.commits + 1 }}` is illegal syntax). I can't find the exact page I read, but this says something similar: https://github.com/actions/checkout/issues/438

I don't know how earlier PRs survived this, but I'm guessing #22 falls to it. There are more complicated ways to be robust about this, but the lazy way seemed to be just `fetch-depth: 0`, and this repository's not very big, so I figured we'd just live with this until actions/checkout supports something more sophisticated 🤓
